name: 'Main - PR Open'
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    types:
      - opened
jobs:
  add_comment:
    name: 'Add Comment'
    runs-on: ubuntu-latest
    steps:
      - uses: mshick/add-pr-comment@v1
        with:
          message: Please set a versioning label of either `major`, `minor`, or `patch` to the pull request.
          repo-token: ${{ secrets.GH_ORG_PAT }}